---
- name: Update repository
  apt: update_cache=yes

- name: python-software-properties
  apt: pkg=python-software-properties state=installed

- name: ACL
  apt: pkg=acl state=installed

- name: cURL
  apt: pkg=curl state=installed

- name: Install Git
  apt: pkg=git-core state=installed

- name: Install mercurial
  apt: pkg=mercurial state=present

- name: Set the hostname /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined