---
- name: Apache 
  apt: pkg=apache2 state=installed

- name: Apache Modules
  command: a2enmod {{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- name: MySQL
  apt: pkg=mysql-server state=installed

- name: MySQL
  apt: pkg=python-mysqldb state=installed

- name: MySQL | Set Root Password
  mysql_user: name={{ dbuser }} host={{ item }} password={{ dbpasswd }} priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

# - name: MySQL | Copy Config File
  # template: src=../files/.my.cnf dest=/{{ dbuser }}/.my.cnf owner={{ dbuser }} mode=0600

- name: MySQL | Create App DB
  mysql_db: name={{ dbname }} state=present login_password={{ dbpasswd }} login_user={{ dbuser }}

- name: MySQL | Install phpmyadmin
  apt: pkg=phpmyadmin state=present

- name: install php
  apt: pkg=libapache2-mod-php5

# - name: install php gd library
#   apt: pkg=php5-gd state=present
#   notify:
#     - restart apache

- name: install php cli
  apt: pkg=php5-cli state=present

- name: install pear
  apt: pkg=php-pear

# - name: install mysql PHP bindings
#   apt: pkg=php5-mysql

# - name: install php-apc
#   apt: pkg=php-apc
#   notify:
#     - restart apache

- name: install SQLite PHP bindings
  apt: pkg=php5-sqlite
  notify:
    - restart apache

# - name: install php curl bindings
#   apt: pkg=php5-curl
#   notify:
#     - restart apache

- name: install php imagick bindings
  apt: pkg=php5-imagick state=present
  notify:
    - restart apache

# - name: install php curl extension
#   apt: pkg=php5-curl state=present
#   notify:
#     - restart apache

- name: install rubygems
  apt: pkg=rubygems state=present

- name: install sass
  gem: name=sass state=present user_install=no

- name: Install memcached
  apt: pkg=memcached state=present

- name: setup python-software-properties
  apt: pkg=python-software-properties state=present

- name: Update apt
  apt: update_cache=yes

- name: setup node apt repo
  apt_repository: repo=ppa:chris-lea/node.js

- name: Install nodejs
  apt: pkg=nodejs state=present

- name: Install grunt cli
  npm: name=grunt-cli state=present global=yes

- name: Install GULP
  npm: name=gulp state=present global=yes

- name: Install GULP phpunit plugin
  npm: name=gulp-phpunit state=present global=yes

- name: Install GULP notify plugin
  npm: name=gulp-notify state=present global=yes

- name: PHP and Modules
  apt: pkg={{ item }} state=latest
  notify: restart apache
  tags: common
  with_items:
    - php5
    - php5-mysql
    - php5-gd
    - php-apc
    - php5-mcrypt
    - php5-curl
    - php5-intl
    - php5-memcached
    - php5-xdebug

# Configurations
- name: Add php5-mcrypt to php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini
              line="extension=mcrypt.so"
              state=present

- name: create /mods-available directory
  file: name=/etc/php5/mods-available state=directory

- name: PHP | Copying XDebug Config
  copy: src=../files/xdebug.ini dest=/etc/php5/mods-available/xdebug.ini
  notify:
    - restart apache

- name: PHP | Config timezone
  ini_file: dest=/etc/php5/mods-available/timezone.ini section=Date option=date.timezone value={{ timezone }}
  notify:
    - restart apache

- name: Install composer
  shell:
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: install git for composer dependencies
  apt: pkg=git state=present
